---
title: "MB5370 Module 4"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Data Science in R


# Assignment 1: Plot De- and Reconstruction
May 2024

Nicoline Winding

Workspace for R code: ~/Documents/github/mb35370-mod4-personal/code/Plot_Deconstruction.R

```{r set-up, eval = TRUE, results="hide"}
#set working directory
setwd("~/Documents")
#read in data extracted from original graph
data <- read.delim("data.txt")
data

str(data)

data$gear <- factor(data$gear)
data$scenario <- factor(data$scenario)

library(tidyverse)
```

```{r graph, eval = TRUE}
#making the graph better
p <- ggplot(data, aes(x=scenario, y=hours, width=.8)) + 
  geom_bar(aes(fill=gear), position=position_dodge(width = 0.9), stat="identity") +
  geom_errorbar(aes(group = gear, x=scenario, ymin=hours-SE, ymax=hours+SE), position=position_dodge(width = 0.9), stat="identity", width=0.2, colour="grey50", alpha=0.9) +
  theme(panel.background = element_rect(fill = "white", colour = "grey50"),
          legend.box.margin = margin(6, 6, 6, 6)) +
  scale_fill_manual(values = c("paleturquoise", "lightsalmon"))+
  scale_color_manual(values =c ("black", "black"))+
  xlab("Scenario") +
  ylab("Hours at sea")

p + labs(fill = "Gear-type")
```

