---
title: "MB5370 Module 4"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Data Science in R

# Assignment 2: Plot De- and Reconstruction
May 2024

Nicoline Winding

```{r set-up, eval = TRUE, results="hide"}
#set working directory is not necessary for a markdown file
#read in data extracted from original graph
shark <- read.delim("../data/Shark.txt")
shark

str(shark)

library(tidyverse)

shark$Area <- factor(shark$Area)
shark$Species <- factor(shark$Species)
```


```{r changing variables, eval = TRUE, r}
#get the mean shark and turtle counts and SE for each year across all the areas
sharkav <- shark |> 
  group_by(Year, Species) |>
  summarise(count_av = mean(Count), 
            SE = sd(Count)/sqrt(length(Count))) 
```


```{r building graph, eval = TRUE, r}
ggplot(shark) +
    geom_point(aes(x = Year, y = Count, color = Species, width=5)) +
    facet_wrap(~ Area)

#different graph - doesn't work
p <- ggplot(shark) +
    geom_point(aes(x = Year, y = Count, color = Species))
    
p + geom_jitter()

#different graph - not right, would need to 
ggplot(shark) +
    geom_line(aes(x = Year, y = Count, color = Species))

#different graph - meh
ggplot(shark, aes(x=Year, y=Count, width=.8)) +
  geom_bar(aes(fill=Species), position=position_dodge(width = 0.9), stat="identity") +
  scale_fill_manual(values = c("lightblue4", "seagreen4"))+
  facet_wrap(~ Area)




ggplot(sharkav, aes(Year, y = count_av, color = Species)) +
  geom_pointrange(aes(ymin = count_av-SE, ymax = count_av+SE)) +
  scale_color_manual(values = c("lightblue4", "seagreen4")) +
  theme(panel.background = element_rect(fill = "white", colour = "grey50"),
          legend.box.margin = margin(6, 6, 6, 6)) +
  xlab("Year") +
  ylab("Mean count +/- SE")


```

how to save plots:
ggsave("../output/FILENAME.jpg", PLOTNAME, width = 3, height = 2)

